### PR TITLE
Enable metal backend on macOS platforms

### LINKED ISSUE #2: Enable Metal rendersystem
### Comment:

Required once:
* https://github.com/gazebosim/gz-sim/pull/1225 

is merged and released.

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #2

### CODE REVIEW

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The only other feedstock that I found that is compiling against metal is PyTorch, and in that case they set also `MACOSX_SDK_VERSION` to an higher version, see https://github.com/conda-forge/pytorch-cpu-feedstock/pull/123/files#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2R1 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
On osx-64 the error is always:
~~~
2022-10-12T10:40:06.3799330Z [ 74%] Linking CXX shared library ../../lib/macosx/RenderSystem_Metal.dylib
2022-10-12T10:40:06.5490980Z ld: framework not found Metal
~~~

even when both MACOSX_DEPLOYMENT_TARGET and MACOSX_SDK_VERSION are set to 12.3 . At this point I am a bit lost, probably I need to read better https://github.com/conda-forge/conda-forge.github.io/issues/1537 .

**Comment by traversaro** [comment]
Actually the conda_build_config.yaml is in the wrong directory, fixed with https://github.com/conda-forge/ogre-next-feedstock/pull/9/commits/d5e10d0f8ba924ee61c04422c34398366bf76a15 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> Actually the conda_build_config.yaml is in the wrong directory, fixed with [d5e10d0](https://github.com/conda-forge/ogre-next-feedstock/commit/d5e10d0f8ba924ee61c04422c34398366bf76a15) .

Also, in the conda-forge.yml file the capitalization of the `vmImage` key was not consistent with what was used in PyTorch .

**Comment by traversaro** [comment]
Ok, now it works. Let's see if just 11.0 works, as that is working for osx_arm64 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by mjcarroll** [comment]
This is fine, everything is fine :upside_down_face:

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
For me we can merge, it is ok for you @mjcarroll ?

**Comment by mjcarroll** [comment]
Great for me! Thanks for iterating!

**Pull request merged**
