### PR TITLE
Fix PLANAR_REFLECTIONS typo

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Thanks @mjcarroll ! To actually make sure that a new version is updated, you need to bump the build number in https://github.com/conda-forge/ogre-next-feedstock/blob/main/recipe/meta.yaml#L21 .

**Comment by mjcarroll** [comment]
> Thanks @mjcarroll ! To actually make sure that a new version is updated, you need to bump the build number in https://github.com/conda-forge/ogre-next-feedstock/blob/main/recipe/meta.yaml#L21 .

Done

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
> > Thanks @mjcarroll ! To actually make sure that a new version is updated, you need to bump the build number in https://github.com/conda-forge/ogre-next-feedstock/blob/main/recipe/meta.yaml#L21 .
> 
> Done

Thanks, ok for me!

**Pull request merged**
