### PR TITLE
Prepare for 2.3.2

### PR DESCRIPTION
**Pull request by mjcarroll**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I have upstream-ed several of these patches.  Once the 2.3.2 tag is added, this should be just about ready to go.

### CODE REVIEW

**Comment by mjcarroll** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Cool! Feel free to add yourself as a mantainer if you like!

**Comment by traversaro** [comment]
Regarding the test failures, I am afraid not all patches are backport that can be removed. I wanted to eventually contribute them upstream, but it was not super clear to me how https://github.com/OGRECave/ogre-next/issues/232 and https://github.com/OGRECave/ogre-next/issues/259 was going, so I decided to do it later (i.e. I forgot to do it, sorry!). Some related (hidden) comments can be found in https://github.com/conda-forge/staged-recipes/pull/19384 .

**Comment by traversaro** [comment]
Looking a bit in the failures, one problem is that upstream Ogre-Next still does not install .pc files on Windows.

**Comment by mjcarroll** [comment]
> One problem is that upstream Ogre-Next still does not install .pc files on Windows.

Yep, I have another local patch for it.  Keeping this draft until we can get it all sorted/ported.

**Comment by mjcarroll** [comment]
I dumped patches from here, which I think will be slightly easier to maintain: https://github.com/gazebo-forks/ogre-next/tree/gazebo/v2-3

**Comment by talregev** [comment]
Any news?

**Comment by traversaro** [comment]
There is no 2.3.2 release for ogre-next .

**Comment by traversaro** [comment]
There is no 2.3.2 release for ogre-next .

**Comment by talregev** [comment]
What version is the next release?

**Comment by traversaro** [comment]
The latest is 2.3.1 and is packaged in conda-forge (see https://github.com/OGRECave/ogre-next/releases), the next one is 2.3.2 or some other version number > 2.3.1, probably ogre-next mantainers will decide that.

**Comment by talregev** [comment]
You mean when ogre-next will be releasing this PR will become relevant?
I thought they want to change something before the release.

Thank you for your details answer.

**Comment by traversaro** [comment]
> You mean when it will be releasing on orge-next side this PR will become relevant?

Yes,  this PR is just a preparation for the next release of ogre-next.

>  I thought they want to change something before the release.

Yes, it is possible more modifications will be necessary, that is why the PR is in draft.

**Comment by mjcarroll** [comment]
Replaced by #18

**Pull request closed without merging**
